export const products = [
  {
    id: 1,
    name: "Move in Move out Cleaning",
    category: "Residential",
    image: "https://cdn.prod.website-files.com/5a4be71aa12183000115e62c/637119599e4b67cd45c241dd_move-out-cleaneing-hero.webp",
  },
  {
    id: 2,
    name: "One Off Cleaning",
    category: "Residential",
    image: "https://img1.wsimg.com/isteam/ip/27aa9fbd-5ae6-4e8f-9d4a-6ee382dbc436/cart%20-%202023-11-13T103012.866.png/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:600,cg:true",
  },
  {
    id: 3,
    name: "Villa Deep Cleaning",
    category: "Residential",
    image: "https://5.imimg.com/data5/SQ/IZ/OH/SELLER-37942208/2000-3000-sq-ft-villa-deep-cleaning.jpg",
  },
  {
    id: 4,
    name: "Building Cleaning",
    category: "Commercial",
    image: "https://media.istockphoto.com/id/1399143321/photo/cleaning-windows-on-a-residential-building.jpg?s=612x612&w=0&k=20&c=5o6RFiKveKMRtXiP8kQr58f21J0_OdoMXsJ8Qqhnjg0=",
  },
  {
    id: 5,
    name: "Hotel and Apartment Cleaning",
    category: "Commercial",
    image: "https://www.markas.com/smartedit/images/news/_published/55a_2.jpg",
  },
  {
    id: 6,
    name: "School and Office Cleaning",
    category: "Commercial",
    image: "https://img.freepik.com/premium-photo/workers-cleaning-service-company-carrying-out-their-work-openspace-office_274679-35142.jpg",
  },
  {
    id: 7,
    name: "Swimming Pool Cleaning",
    category: "Outdoor",
    image: "https://www.royalblackservices.com/assets/img/big-images/5Swimming-Pools-Cleaning.jpg",
  },
  {
    id: 8,
    name: "General Domestic Cleaning",
    category: "Residential",
    image: "https://nextdaycleaning.com/wp-content/uploads/2021/09/General-Cleaning-Checklist-For-All-House-Areas.jpg",
  },
  {
    id: 9,
    name: "General Maintenance",
    category: "Commercial",
    image: "https://alpinemaintenance.com/wp-content/uploads/2022/09/emergencyp-clean.jpeg",
  },
  {
    id: 10,
    name: "Event Manpower Supply",
    category: "Commercial",
    image: "https://5.imimg.com/data5/SELLER/Default/2023/3/SJ/LO/ZR/2164686/housekeeping-manpower-services-500x500.jpg",
  },
  {
    id: 11,
    name: "Carpet Cleaning",
    category: "Furniture",
    image: "https://img.choice.com.au/-/media/74fe12e385064f56baa7164473f2ca20.ashx",
  },
  {
    id: 12,
    name: "Wet and Dry Cleaning of Beds and Sofas",
    category: "Furniture",
    image: "https://img.freepik.com/premium-photo/dry-cleaning-home-furniture-with-extractor-cleaner-is-washing-off-sofa-cushions-with-extractor-drying-soft-upholstered-headboard-bed-using-dryer-remove-wet-spots-bed_255847-13584.jpg",
  },
  {
    id: 13,
    name: "Sterilization Services",
    category: "Residential",
    image: "https://anneer.com/wp-content/uploads/2024/04/AN-Neer-Disinfecting-010.webp",
  },
  {
    id: 14,
    name: "Car Wash Services",
    category: "Vehicle",
    image: "https://www.yashautomedik.com/wp-content/uploads/2022/12/How-To-Select-The-Best-Car-Cleaning-Products-1200x800.jpg",
  },
  {
    id: 15,
    name: "Sofa Cleaning",
    category: "Furniture",
    image: "https://media.angi.com/s3fs-public/Man-professionally-cleaning-couch.jpg?impolicy=leadImage",
  },
  {
    id: 16,
    name: "Moving and Packing",
    category: "Residential",
    image: "https://images.squarespace-cdn.com/content/v1/5c19abcde74940df765ba7e9/0d4a87ce-9c3e-41b2-a57e-9a485b8c35fc/items-to-be-moved-some-boxed-some-not.jpg",
  },
];
